// Package Declaration
package Calculator

// Imports Begin
import std.collection.*
import std.io.*
// Imports End

class HistoryLogger {
	// Class Fields Begin
	internal var history: Array<String> = []
	// Class Fields End

	// Class Methods Begin
	public func clear(): Unit {
		// TODO
	}
	public func getHistory(): Array<String> {
		// TODO
	}
	public func log(operation: String, result: Int64): Unit {
		// TODO
	}
	// Class Methods End

}

