// Package Declaration
package org.apache.commons.fileupload

// Imports Begin
import org/apache/commons/fileupload/disk/DiskFileItem
import std.os.*
import std.reflect.*
import std.io.*
// Imports End

class DefaultFileItem <:DiskFileItem {
	// Class Fields Begin
	// Class Fields End

	// Class Methods Begin
	public init(fieldName: String, contentType: String, isFormField: Bool, fileName: String, sizeThreshold: Int64, repository: ) {
		// TODO
	}
	// Class Methods End

}

