// Package Declaration
package org.apache.commons.fileupload

// Imports Begin
import org/apache/commons/fileupload/disk/DiskFileItemFactory
import std.os.*
import std.io.*
// Imports End

class DefaultFileItemFactory <:DiskFileItemFactory {
	// Class Fields Begin
	// Class Fields End

	// Class Methods Begin
	public init(sizeThreshold: Int64, repository: ) {
		// TODO
	}
	public static func DefaultFileItemFactory1(): DefaultFileItemFactory {
		// TODO
	}
	// Class Methods End

}

