// Package Declaration
package simple-calculator

// Imports Begin
import calculator.HistoryLogger
import calculator.Calculator
import std.io.*
// Imports End

class CalculatorTest {
	// Class Fields Begin
	internal var calculator: Calculator = ?
	// Class Fields End

	// Class Methods Begin
	internal func testHistoryLogging(): Unit {
		// TODO
	}
	internal func testInvalidInput(): Unit {
		// TODO
	}
	internal func testPerformDiv(): Unit {
		// TODO
	}
	internal func testPerformMul(): Unit {
		// TODO
	}
	internal func testPerformSub(): Unit {
		// TODO
	}
	internal func testPerformAdd(): Unit {
		// TODO
	}
	internal func setUp(): Unit {
		// TODO
	}
	// Class Methods End

}

