// Package Declaration
package org.apache.commons.fileupload.util.mime

// Imports Begin
import std.collection.*
import std.io.*
// Imports End

class QuotedPrintableDecoder {
	// Class Fields Begin
	static let UPPER_NIBBLE_SHIFT: Int64 = ?
	// Class Fields End

	// Class Methods Begin
	public static func decode(data: Array<Int8>, out: ): Int64 {
		// TODO
	}
	internal static func hexToBinary(b: Int8): Int64 {
		// TODO
	}
	internal init() {
		// TODO
	}
	// Class Methods End

}

