// Package Declaration
package test.java.org.apache.commons.fileupload

// Imports Begin
import std.os.*
import std.collection.*
import std.any.*
import std.reflect.*
import std.io.*
// Imports End

class DiskFileItemSerializeTest {
	// Class Fields Begin
	static let REPO:  = ?
	static let textContentType: String = ?
	static let threshold: Int64 = ?
	// Class Fields End

	// Class Methods Begin
	internal func deserialize(baos: ): Any {
		// TODO
	}
	internal func serialize(target: Any):  {
		// TODO
	}
	internal func createContentBytes(size: Int64): Array<Int8> {
		// TODO
	}
	internal func compareBytes(text: String, origBytes: Array<Int8>, newBytes: Array<Int8>): Unit {
		// TODO
	}
	// Class Methods End

}

