// Package Declaration
package test.java.org.apache.commons.fileupload

// Imports Begin
import org/apache/commons/fileupload/ProgressListener
import org/apache/commons/fileupload/MultipartStream
import std.io.*
// Imports End

@Test
class MultipartStreamTest {
	// Class Fields Begin
	static let BOUNDARY_TEXT: String = ?
	// Class Fields End

	// Class Methods Begin
	public func testTwoParamConstructor(): Unit {
		// TODO
	}
	public func testSmallBuffer(): Unit {
		// TODO
	}
	public func testThreeParamConstructor(): Unit {
		// TODO
	}
	// Class Methods End

}

