// Package Declaration
package test.java.calculator

// Imports Begin
import calculator/Arithmetics
import std.io.*
// Imports End

class ArithmeticsTest {
	// Class Fields Begin
	internal let arithmetics: Arithmetics = ?
	// Class Fields End

	// Class Methods Begin
	internal func testDivByZero(): Unit {
		// TODO
	}
	internal func testDiv(): Unit {
		// TODO
	}
	internal func testMul(): Unit {
		// TODO
	}
	internal func testSub(): Unit {
		// TODO
	}
	internal func testAdd(): Unit {
		// TODO
	}
	// Class Methods End

}

