// Package Declaration
package Calculator.test

// Imports Begin
import calculator.Arithmetics
import std.io.*
// Imports End

class ArithmeticsTest {
	// Class Fields Begin
	internal var arithmetics: Arithmetics = ?
	// Class Fields End

	// Class Methods Begin
	internal func testDivByZero(): Unit {
		// TODO
	}
	internal func testDiv(): Unit {
		// TODO
	}
	internal func testMul(): Unit {
		// TODO
	}
	internal func testSub(): Unit {
		// TODO
	}
	internal func testAdd(): Unit {
		// TODO
	}
	// Class Methods End

}

