// Package Declaration
package fileupload

// Imports Begin
import std.collection.*
import std.reflect.*
import std.io.*
// Imports End

class DefaultFileItemTest {
	// Class Fields Begin
	static let RUSSIAN_STUFF_WIN1251: Array<Int64> = ?
	static let textContentType: String = ?
	static let fileContentType: String = ?
	static let threshold: Int64 = ?
	static let CHARSET_ISO88591: String = ?
	static let CHARSET_ASCII: String = ?
	static let CHARSET_UTF8: String = ?
	static let CHARSET_KOI8_R: String = ?
	static let CHARSET_WIN1251: String = ?
	static let SWISS_GERMAN_STUFF_UNICODE: Array<Int64> = ?
	static let SWISS_GERMAN_STUFF_ISO8859_1: Array<Int64> = ?
	static let SWISS_GERMAN_STUFF_UTF8: Array<Int64> = ?
	static let RUSSIAN_STUFF_UNICODE: Array<Int64> = ?
	static let RUSSIAN_STUFF_UTF8: Array<Int64> = ?
	static let RUSSIAN_STUFF_KOI8R: Array<Int64> = ?
	// Class Fields End

	// Class Methods Begin
	internal static func constructString(unicodeChars: Array<Int64>): String {
		// TODO
	}
	// Class Methods End

}

