// Package Declaration
package test.java.calculator

// Imports Begin
import calculator.HistoryLogger
import std.io.*
// Imports End

class HistoryLoggerTest {
	// Class Fields Begin
	internal var logger: HistoryLogger = ?
	// Class Fields End

	// Class Methods Begin
	internal func testGetHistoryReturnsCopy(): Unit {
		// TODO
	}
	internal func testClear(): Unit {
		// TODO
	}
	internal func testMultipleLogs(): Unit {
		// TODO
	}
	internal func testLog(): Unit {
		// TODO
	}
	internal func setUp(): Unit {
		// TODO
	}
	// Class Methods End

}

