// Package Declaration
package fileupload.util.mime

// Imports Begin
import util.mime.MimeUtility
import std.io.*
// Imports End

@Test
class MimeUtilityTestCase {
	// Class Fields Begin
	// Class Fields End

	// Class Methods Begin
	public func decodeInvalidEncoding(): Unit {
		// TODO
	}
	public func decodeIso88591Base64EncodedWithWhiteSpace(): Unit {
		// TODO
	}
	public func decodeIso88591Base64Encoded(): Unit {
		// TODO
	}
	public func decodeUtf8Base64Encoded(): Unit {
		// TODO
	}
	public func decodeUtf8QuotedPrintableEncoded(): Unit {
		// TODO
	}
	public func noNeedToDecode(): Unit {
		// TODO
	}
	internal static func assertEncoded(expected: String, encoded: String): Unit {
		// TODO
	}
	// Class Methods End

}

