// Package Declaration
package fileupload.util.mime

// Imports Begin
import util.mime.QuotedPrintableDecoder
import std.io.*
// Imports End

@Test
class QuotedPrintableDecoderTestCase {
	// Class Fields Begin
	static let US_ASCII_CHARSET: String = ?
	// Class Fields End

	// Class Methods Begin
	public func truncatedEscape(): Unit {
		// TODO
	}
	public func invalidSoftBreak2(): Unit {
		// TODO
	}
	public func invalidSoftBreak1(): Unit {
		// TODO
	}
	public func softLineBreakDecode(): Unit {
		// TODO
	}
	public func invalidCharDecode(): Unit {
		// TODO
	}
	public func unsafeDecodeLowerCase(): Unit {
		// TODO
	}
	public func unsafeDecode(): Unit {
		// TODO
	}
	public func invalidQuotedPrintableEncoding(): Unit {
		// TODO
	}
	public func basicEncodeDecode(): Unit {
		// TODO
	}
	public func plainDecode(): Unit {
		// TODO
	}
	public func emptyDecode(): Unit {
		// TODO
	}
	internal static func assertIOException(messageText: String, encoded: String): Unit {
		// TODO
	}
	internal static func assertEncoded(clearText: String, encoded: String): Unit {
		// TODO
	}
	// Class Methods End

}

