// Package Declaration
package org.apache.commons.fileupload.portlet

// Imports Begin
import org/apache/commons/fileupload/FileUpload
import org/apache/commons/fileupload/FileItemFactory
import std.io.*
// Imports End

class PortletFileUpload <:FileUpload {
	// Class Fields Begin
	// Class Fields End

	// Class Methods Begin
	public static func PortletFileUpload1(): PortletFileUpload {
		// TODO
	}
	public init(fileItemFactory: FileItemFactory) {
		// TODO
	}
	// Class Methods End

}

