// Package Declaration
package HelloWorld.test

// Imports Begin
import HelloWorld.HelloWorld
import std.collection.*
import std.io.*
// Imports End

@Test
class HelloWorldTest {
	// Class Fields Begin
	// Class Fields End


	// Class Methods Begin
	public func testMain(): Unit {
		throw Exception('TODO')
	}
	// Class Methods End

}

main(args: Array<String>): Int64 {
    // dummy main (original source doesn't have main)
    0
}
