// Package Declaration
package org.apache.commons.fileupload.util

// Imports Begin
import InvalidFileNameException
import std.io.*
// Imports End

class Streams {
	// Class Fields Begin
	public static let DEFAULT_BUFFER_SIZE: Int64 = ?
	// Class Fields End

	// Class Methods Begin
	public static func checkFileName(fileName: String): String {
		// TODO
	}
	internal init() {
		// TODO
	}
	// Class Methods End

}

