// Package Declaration
package org.apache.commons.fileupload

// Imports Begin
import std.io.*
// Imports End

class InvalidFileNameException <: {
	// Class Fields Begin
	static let serialVersionUID: Int64 = ?
	internal let name: String = ""
	// Class Fields End

	// Class Methods Begin
	public func getName(): String {
		// TODO
	}
	public init(pName: String, pMessage: String) {
		// TODO
	}
	// Class Methods End

}

